### ISSUE TITLE
Guard memory allocations with try-finally-end blocks

### ISSUE THREAD

**Issue by beNative** [t-edson/SynFacilSyn#13]
Hi,

I noticed in the code that many objects are created without guarding them.

example:

``` Pascal
var
  Idens  : TStringList;
  iden   : string;
  i      : integer;
begin
  Idens :=TStringList.Create;
  Idens.Delimiter := ' ';
  //StringReplace(listSym, #13#10, ' ',[rfReplaceAll]);
  IDens.DelimitedText := listSym;
  for i:= 0 to IDens.Count -1 do
    begin
      iden := trim(IDens[i]);
      if iden = '' then continue;
      AddSymbSpec(iden, tokTyp, TokPos);
      if Err <> '' then break;
    end;
  Idens.Free;  
```

better would be:

``` Pascal
var
  Idens  : TStringList;
  iden   : string;
  i      : integer;
begin
  //Carga identificadores
  Idens :=TStringList.Create;
  try
    Idens.Delimiter := ' ';
    //StringReplace(listSym, #13#10, ' ',[rfReplaceAll]);
    IDens.DelimitedText := listSym;
    for i:= 0 to IDens.Count -1 do
      begin
        iden := trim(IDens[i]);
        if iden = '' then continue;
        AddSymbSpec(iden, tokTyp, TokPos);
        if Err <> '' then break;
      end;
  finally
    Idens.Free;
  end;
end;
```

I recommend you apply this pattern to all dynamically created objects in your code. By this you guarantee proper cleanup of allocated memory in the event of an exception

One notable exception of course are class members that are created in the constructor. They are guaranteed to be cleaned up by the destructor in the event of an exception. 
I would also recommend to use Free instead of Destroy. Calling Free checks if the object is not Nil and then calls Destroy accordingly. It's safe. Just calling Destroy will not check if the involved object is nil so it might trigger an access violation.

Regards,
Tim

**Comment by t-edson** [comment]
I don't use this pattern to much because of:
- It's no so common to have memory problems when using highlighters. I have never had, but I know it could happens.
- In the case if happens, using Free, could help on releasing the memory used, but it's almost sure that this error will cause an exception later because most of this steps are critical for the next step.
- Object Pascal hasn't a compact syntax, so including aditional structures make the code less legible.  I had noted several times on the forum that the syntax is very old and complicated (http://forum.lazarus.freepascal.org/index.php/topic,22790.msg135397.html#msg135397, http://forum.lazarus.freepascal.org/index.php/topic,22777.msg135091.html#msg135091, http://forum.lazarus.freepascal.org/index.php/topic,13754.msg134244.html#msg134244, http://forum.lazarus.freepascal.org/index.php/topic,24271.msg146073.html#msg146073, ...). 

The possible error on allocating objects, is one of the reasons I don't like using objects. I would prefer using static variables. I don't know why there is not a simple static list in FreePascal (http://forum.lazarus.freepascal.org/index.php/topic,22231.msg144198.html#msg144198). Anyway this is out of topic.

I will consider to include this protection, analyzing every case, but probably I will end using a global list, for to avoid create and destroy many times.

**Comment by t-edson** [comment]
It has been replaced the use of a local list in ValidateParams(), AddIdentSpecList() y
AddSymbSpecList(). Now they use the temporal list "lisTmp" instead. You can see it on the 0.9.5b.

**Comment by beNative** [comment]
I'm not sure what you mean with 'static lists', but Pascal does support both static (fixed size) and dynamic arrays (any size).
As for creating/freeïng objects it's just good coding practice to always guard them, really! If you want less boilerplate you can use interface variables instead of objects, which will be freed automatically when they run out of scope. 
In this respect Object Pascal does not differ very much from C++, Objective C, Java or C#. Just another syntax to do the same thing.

**Comment by t-edson** [comment]
With "Static List", I refered to some kind of "TSTringList", that can be created in the Stack like a common variable.
Interface variables, still need to be created after declared, and they need extra code.
