### ISSUE TITLE
fix rule for Hex, in Pas lexer

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/SynFacilSyn#26]
$ffor must not be hex number
![fac](https://user-images.githubusercontent.com/4154978/56849561-cfdf2380-68fe-11e9-8fb1-16287ace12d3.png)

**Comment by t-edson** [comment]
I really have not idea what you mean. Please explain.

**Comment by Alexey-T** [comment]
SynFacil finds token "$ff" even if its inside "$ffor". it must ignore "$ff" here.

**Comment by t-edson** [comment]
What syntax XML file are you using?

**Comment by Alexey-T** [comment]
I run demo SynFacil+ATsynedit.

**Comment by t-edson** [comment]
I see. It's because of token definition in the "Pascal.xml" file:

`<Token CharsStart="$" Content = '0..9ABCDEFabcdef' Attribute='NUMBER'> </Token>`
 
It consider all tokens started with "$" like a number, including the following [0.9abcdef] chars.
An accurate definiiton could be possible, but it will be more complex
